---
- hosts: localhost
  tasks:
  - name: Install essential packages
    become: yes
    apt:
      name: 
        - build-essential
        - net-tools
        - apt-transport-https
        - build-essential
        - chrome-gnome-shell
        - cpu-checker
        - curl
        - firefox-locale-ko
        - fonts-firacode
        - fonts-noto-cjk-extra
        - git
        - gnome-tweaks
        - gnupg-agent
        - ibus-hangul
        - ibus-unikey
        - language-pack-gnome-ko
        - ocs-url
        - python3-dev
        - python3-pip
        - python3-setuptools
        - virtualbox-6.0
        - whois
        - zsh

  - name: Install snaps
    become: yes
    snap:
      name:
        - android-studio
        - chromium
        - clion
        - mailspring
        - pinta
        - slack
        - spotify
        - terminus
        - tilix
        - vscode

  - name: download oh-my-zsh
    git: repo=git://github.com/robbyrussell/oh-my-zsh.git
        dest=~/.oh-my-zsh accept_hostkey=true
    when: omz_bound|failed

  - name: change shell
    command: chsh -s /bin/zsh
    when: omz_bound|failed

  - name: Install prerequisites
    become: yes
    apt:
      name: ['apt-transport-https', 'ca-certificates', 'curl', 'gnupg2' ,'software-properties-common']
      update_cache: yes

  - name: Add Docker GPG apt Key
    become: yes  
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present

  - name: Add Docker Repository
    become: yes  
    apt_repository:
      repo: deb https://download.docker.com/linux/ubuntu bionic stable
      state: present

  - name: Update apt and install docker-ce
    become: yes  
    apt:
      update_cache: yes 
      name: docker-ce 
      state: latest

  - name: Update apt and install docker-ce
    become: yes  
    apt:
      update_cache: no
      name: docker-compose
      state: latest

  # sudo groupadd docker
  - name: Create "docker" group
    become: yes  
    group:
      name: docker
      state: present
  
  # sudo usermod -aG docker ubuntu
  - name: Add remote "ubuntu" user to "docker" group
    become: yes  
    user:
      name: thanhphu
      group: docker
      append: yes

  # sudo apt-get autoclean
  - name: Remove useless apt packages from the cache
    become: yes  
    apt:
      autoclean: yes
  
  # sudo apt-get autoremove
  - name: Remove dependencies that are no longer required
    become: yes  
    apt:
      autoremove: yes

  - name: Load gnome config
    shell: dconf load / < saved_settings.dconf